package ru.profitsw2000.utils

const val SHARED_PREFERENCE_NAME = "SHARED_PREFERENCE_NAME"

const val LAST_FRAGMENT_KEY = "last_opened_fragment"
const val IS_GENERAL_CALCULATOR = 1
const val IS_SCIENTIFIC_CALCULATOR = 2
const val IS_PROGRAMMER_CALCULATOR = 3
const val IS_STATISTIC_CALCULATOR = 4
const val IS_UNIT_CONVERSION_SHEET = 5
const val IS_DATE_CALCULATION_SHEET = 6
const val IS_MORTGAGE_SHEET = 7
const val IS_AUTO_LEASING_SHEET = 8
const val IS_FUEL_ECONOMY_SHEET = 9

